import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, View } from "react-native";

import { ScreenContainer } from "@/components/screen-container";
import { deleteDownload, listDownloads, type DownloadedAudio } from "@/lib/downloads";
import { usePlayer } from "@/lib/player-context";
import { useQuranTheme } from "@/lib/quran-theme";

const formatBytes = (bytes: number) => bytes < 1024 * 1024 ? `${Math.max(1, Math.round(bytes / 1024))} كيلوبايت` : `${(bytes / (1024 * 1024)).toFixed(1)} م.ب`;
export default function DownloadsScreen() { const router = useRouter(); const { colors } = useQuranTheme(); const { playItem } = usePlayer(); const [items, setItems] = useState<DownloadedAudio[]>([]); const [loading, setLoading] = useState(true); const load = useCallback(async () => { setLoading(true); setItems(await listDownloads()); setLoading(false); }, []); useFocusEffect(useCallback(() => { void load(); }, [load])); return <ScreenContainer style={{ backgroundColor: colors.background }}><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} renderItem={({ item }) => <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Pressable onPress={() => void playItem({ id: item.id, title: item.title, subtitle: item.subtitle, streamUrl: item.localUri, kind: "reciter", category: "تنزيلات", color: colors.emerald })} style={styles.main}><MaterialCommunityIcons name="play-circle" size={31} color={colors.emerald} /><View style={styles.copy}><Text numberOfLines={1} style={[styles.title, { color: colors.text }]}>{item.title}</Text><Text numberOfLines={1} style={[styles.meta, { color: colors.textMuted }]}>{item.subtitle} · {formatBytes(item.size)}</Text></View></Pressable><Pressable onPress={async () => { await deleteDownload(item.id); await load(); }} style={styles.delete}><MaterialCommunityIcons name="trash-can-outline" size={20} color={colors.danger} /></Pressable></View>} ListHeaderComponent={<View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.icon, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialCommunityIcons name="chevron-right" size={25} color={colors.text} /></Pressable><View><Text style={[styles.heading, { color: colors.text }]}>التنزيلات</Text><Text style={[styles.subheading, { color: colors.textMuted }]}>تلاوات محفوظة للاستماع دون اتصال</Text></View></View>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surfaceMuted }]}>{loading ? <ActivityIndicator color={colors.emerald} /> : <><MaterialCommunityIcons name="download-off-outline" size={31} color={colors.gold} /><Text style={[styles.emptyText, { color: colors.textMuted }]}>لا توجد تنزيلات بعد. افتح قارئًا واختر السورة ثم اضغط زر التنزيل.</Text></>}</View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 40 }, header: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between", marginBottom: 22 }, icon: { width: 42, height: 42, borderRadius: 15, borderWidth: 1, justifyContent: "center", alignItems: "center" }, heading: { textAlign: "right", fontWeight: "900", fontSize: 26 }, subheading: { textAlign: "right", fontSize: 12, marginTop: 3 }, card: { minHeight: 72, borderRadius: 20, borderWidth: 1, padding: 11, flexDirection: "row-reverse", alignItems: "center", marginBottom: 9 }, main: { flex: 1, flexDirection: "row-reverse", alignItems: "center" }, copy: { flex: 1, alignItems: "flex-end", marginHorizontal: 10 }, title: { width: "100%", textAlign: "right", fontWeight: "900", fontSize: 14 }, meta: { width: "100%", textAlign: "right", fontSize: 11, marginTop: 4 }, delete: { width: 30, alignItems: "center" }, empty: { borderRadius: 22, alignItems: "center", padding: 24, gap: 10 }, emptyText: { textAlign: "center", fontSize: 12, lineHeight: 19 } });
