import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useRouter } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";

import { ArtworkOrb } from "@/components/artwork-orb";
import { ScreenContainer } from "@/components/screen-container";
import { usePlayer } from "@/lib/player-context";
import { useQuranTheme } from "@/lib/quran-theme";

export default function PlayerScreen() {
  const router = useRouter(); const { colors } = useQuranTheme(); const { current, isPlaying, error, favorites, togglePlayback, stopPlayback, reconnect, toggleFavorite } = usePlayer();
  if (!current) return <ScreenContainer style={{ backgroundColor: colors.background }}><View style={styles.empty}><MaterialCommunityIcons name="radio-off" size={42} color={colors.gold} /><Text style={[styles.emptyText, { color: colors.textMuted }]}>اختر إذاعة أو سورة لتبدأ الاستماع.</Text><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: colors.emerald }]}><Text style={styles.backText}>عودة</Text></Pressable></View></ScreenContainer>;
  const favorite = favorites.includes(current.id); const live = current.kind === "station" || current.kind === "story";
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={{ backgroundColor: colors.background }}><View style={styles.content}><View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.icon, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><MaterialCommunityIcons name="chevron-down" size={26} color={colors.text} /></Pressable><Text style={[styles.topLabel, { color: colors.textMuted }]}>{live ? "بث مباشر" : "تلاوة محفوظة"}</Text><Pressable onPress={() => toggleFavorite(current.id)} style={({ pressed }) => [styles.icon, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><MaterialCommunityIcons name={favorite ? "heart" : "heart-outline"} size={22} color={favorite ? colors.gold : colors.text} /></Pressable></View><View style={[styles.art, { backgroundColor: current.color }]}><Text style={styles.glyph}>۞</Text><ArtworkOrb color="rgba(255,255,255,.14)" kind={current.kind} size={142} /></View><View style={styles.copy}><Text numberOfLines={2} style={[styles.title, { color: colors.text }]}>{current.title}</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>{current.subtitle}</Text>{live ? <View style={[styles.live, { backgroundColor: colors.emeraldSoft }]}><View style={[styles.dot, { backgroundColor: colors.emerald }]} /><Text style={[styles.liveText, { color: colors.emerald }]}>مصدر مباشر</Text></View> : null}</View><View style={styles.controls}><Pressable onPress={() => void reconnect()} style={({ pressed }) => [styles.minor, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><MaterialCommunityIcons name="reload" size={26} color={colors.gold} /></Pressable><Pressable onPress={togglePlayback} style={({ pressed }) => [styles.primary, { backgroundColor: colors.emerald }, pressed && styles.pressed]}><MaterialCommunityIcons name={isPlaying ? "pause" : "play"} size={38} color="#FFF" /></Pressable><Pressable onPress={stopPlayback} style={({ pressed }) => [styles.minor, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><MaterialCommunityIcons name="stop" size={24} color={colors.danger} /></Pressable></View><View style={styles.labels}><Text style={[styles.controlLabel, { color: colors.textMuted }]}>إعادة الاتصال</Text><Text style={[styles.controlLabel, { color: colors.textMuted }]}>{isPlaying ? "إيقاف مؤقت" : "تشغيل"}</Text><Text style={[styles.controlLabel, { color: colors.textMuted }]}>إيقاف</Text></View>{error ? <View style={[styles.error, { backgroundColor: colors.goldSoft }]}><Text style={[styles.errorText, { color: colors.text }]}>{error}</Text><Pressable onPress={() => void reconnect()}><Text style={[styles.retryText, { color: colors.emerald }]}>حاول إعادة الاتصال</Text></Pressable></View> : null}</View></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { flex: 1, padding: 20, alignItems: "center" }, top: { width: "100%", flexDirection: "row-reverse", justifyContent: "space-between", alignItems: "center" }, topLabel: { fontSize: 11, fontWeight: "800" }, icon: { width: 42, height: 42, borderRadius: 15, borderWidth: 1, alignItems: "center", justifyContent: "center" }, art: { width: "100%", aspectRatio: 1, maxHeight: 310, marginTop: 38, borderRadius: 38, alignItems: "center", justifyContent: "center", overflow: "hidden" }, glyph: { position: "absolute", color: "rgba(255,255,255,.14)", fontSize: 270, lineHeight: 300 }, copy: { width: "100%", marginTop: 28, alignItems: "center" }, title: { textAlign: "center", fontSize: 25, lineHeight: 34, fontWeight: "900" }, subtitle: { textAlign: "center", marginTop: 7, fontSize: 13 }, live: { marginTop: 14, height: 31, borderRadius: 12, paddingHorizontal: 12, flexDirection: "row-reverse", alignItems: "center", gap: 7 }, dot: { width: 7, height: 7, borderRadius: 4 }, liveText: { fontSize: 11, fontWeight: "800" }, controls: { marginTop: 42, width: "100%", flexDirection: "row-reverse", justifyContent: "center", alignItems: "center", gap: 26 }, primary: { width: 78, height: 78, borderRadius: 39, alignItems: "center", justifyContent: "center" }, minor: { width: 50, height: 50, borderRadius: 17, borderWidth: 1, alignItems: "center", justifyContent: "center" }, labels: { width: "100%", paddingHorizontal: 12, marginTop: 8, flexDirection: "row-reverse", justifyContent: "space-between" }, controlLabel: { fontSize: 10, fontWeight: "700" }, error: { marginTop: 28, width: "100%", borderRadius: 16, padding: 13, alignItems: "center", gap: 7 }, errorText: { textAlign: "center", fontSize: 12, lineHeight: 18 }, retryText: { fontWeight: "900", fontSize: 12 }, pressed: { opacity: .74, transform: [{ scale: .97 }] }, empty: { flex: 1, alignItems: "center", justifyContent: "center", padding: 28, gap: 14 }, emptyText: { textAlign: "center", fontSize: 15 }, back: { paddingHorizontal: 20, height: 44, borderRadius: 15, justifyContent: "center" }, backText: { color: "#FFF", fontWeight: "800" } });
