import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { ArtworkOrb } from "@/components/artwork-orb";
import { ScreenContainer } from "@/components/screen-container";
import { downloadAudio } from "@/lib/downloads";
import { getSurahAudioItem } from "@/lib/quran-catalog";
import { usePlayer } from "@/lib/player-context";
import { useQuranContent } from "@/lib/quran-content-context";
import { useQuranTheme } from "@/lib/quran-theme";

export default function ReciterDetailsScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const router = useRouter();
  const { colors } = useQuranTheme();
  const { catalog, loading } = useQuranContent();
  const { current, isPlaying, playItem, resumePositions } = usePlayer();
  const [query, setQuery] = useState("");
  const [selectedMoshafId, setSelectedMoshafId] = useState("");
  const [downloading, setDownloading] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const reciter = catalog?.reciters.find((item) => item.id === id);
  const selectedMoshaf = reciter?.moshafs.find((item) => item.id === selectedMoshafId) ?? reciter?.moshafs.find((item) => item.id === reciter.defaultMoshafId);
  const surahs = useMemo(() => selectedMoshaf && catalog ? catalog.surahs.filter((surah) => selectedMoshaf.availableSurahIds.includes(surah.number) && surah.name.includes(query.trim())) : [], [catalog, query, selectedMoshaf]);
  if (!reciter || !catalog) return <ScreenContainer style={{ backgroundColor: colors.background }}><View style={styles.center}>{loading ? <ActivityIndicator color={colors.emerald} /> : <Text style={[styles.message, { color: colors.textMuted }]}>لا توجد بيانات قارئ معتمدة بهذا المعرّف.</Text>}<Pressable onPress={() => router.back()} style={[styles.backAction, { backgroundColor: colors.emerald }]}><Text style={styles.backText}>عودة</Text></Pressable></View></ScreenContainer>;
  return <ScreenContainer style={{ backgroundColor: colors.background }}><FlatList data={surahs} keyExtractor={(surah) => surah.number.toString()} contentContainerStyle={styles.content} renderItem={({ item }) => {
    const audio = getSurahAudioItem(reciter, item, selectedMoshaf?.id);
    if (!audio) return null;
    const playing = current?.id === audio.id && isPlaying; const resume = resumePositions[audio.id]?.positionSeconds ?? 0;
    return <View style={[styles.surah, { backgroundColor: colors.surface, borderColor: playing ? colors.emerald : colors.border }]}><Pressable onPress={() => void playItem(audio)} style={({ pressed }) => [styles.surahMain, pressed && styles.pressed]}><View style={[styles.number, { backgroundColor: colors.emeraldSoft }]}><Text style={[styles.numberText, { color: colors.emerald }]}>{item.number}</Text></View><View style={styles.surahCopy}><Text style={[styles.surahTitle, { color: colors.text }]}>{item.name}</Text><Text style={[styles.surahMeta, { color: colors.textMuted }]}>{resume > 3 ? `متابعة من ${Math.floor(resume / 60)}:${String(Math.floor(resume % 60)).padStart(2, "0")}` : `${item.numberOfAyahs} آية · ${item.revelationType === "Meccan" ? "مكية" : "مدنية"}`}</Text></View><MaterialCommunityIcons name={playing ? "pause" : "play"} size={22} color={colors.emerald} /></Pressable><Pressable onPress={async () => { try { setDownloading(audio.id); const result = await downloadAudio(audio); setNotice(`تم حفظ ${result.title} للتشغيل دون اتصال.`); } catch { setNotice("تعذر تنزيل السورة. تحقق من الاتصال وحاول مجددًا."); } finally { setDownloading(null); } }} style={({ pressed }) => [styles.download, pressed && styles.pressed]}><MaterialCommunityIcons name={downloading === audio.id ? "progress-download" : "download-outline"} size={21} color={colors.gold} /></Pressable></View>;
  }} ListHeaderComponent={<View><View style={styles.top}><Pressable onPress={() => router.back()} style={[styles.icon, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialCommunityIcons name="chevron-right" size={25} color={colors.text} /></Pressable><Text style={[styles.topLabel, { color: colors.textMuted }]}>السور المتاحة</Text></View><View style={[styles.hero, { backgroundColor: colors.emeraldSoft }]}><ArtworkOrb color={colors.emerald} kind="reciter" size={74} /><Text style={[styles.reciterName, { color: colors.text }]}>{reciter.name}</Text><Text style={[styles.reciterMeta, { color: colors.textMuted }]}>{surahs.length} سورة متاحة للاستماع</Text></View><View style={styles.moshafRow}>{reciter.moshafs.map((moshaf) => <Pressable key={moshaf.id} onPress={() => setSelectedMoshafId(moshaf.id)} style={({ pressed }) => [styles.moshafChip, { backgroundColor: selectedMoshaf?.id === moshaf.id ? colors.emerald : colors.surface, borderColor: selectedMoshaf?.id === moshaf.id ? colors.emerald : colors.border }, pressed && styles.pressed]}><Text style={[styles.moshafText, { color: selectedMoshaf?.id === moshaf.id ? "#FFF" : colors.text }]}>{moshaf.name}{moshaf.rewaya ? ` · ${moshaf.rewaya}` : ""}</Text></Pressable>)}</View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialCommunityIcons name="magnify" size={21} color={colors.textMuted} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث باسم السورة" placeholderTextColor={colors.textMuted} style={[styles.input, { color: colors.text }]} textAlign="right" returnKeyType="done" /></View>{notice ? <Text style={[styles.notice, { color: colors.gold }]}>{notice}</Text> : null}</View>} showsVerticalScrollIndicator={false} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 44 }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: 14 }, message: { fontSize: 14 }, backAction: { height: 42, borderRadius: 14, paddingHorizontal: 18, justifyContent: "center" }, backText: { color: "#FFF", fontWeight: "800" }, top: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, icon: { width: 42, height: 42, borderRadius: 15, borderWidth: 1, justifyContent: "center", alignItems: "center" }, topLabel: { fontSize: 11, fontWeight: "800" }, hero: { borderRadius: 28, alignItems: "center", padding: 22, marginTop: 20 }, reciterName: { fontSize: 22, fontWeight: "900", marginTop: 12 }, reciterMeta: { fontSize: 12, marginTop: 4 }, moshafRow: { flexDirection: "row-reverse", flexWrap: "wrap", justifyContent: "flex-start", gap: 8, marginTop: 13 }, moshafChip: { borderWidth: 1, borderRadius: 14, paddingHorizontal: 11, paddingVertical: 9 }, moshafText: { fontSize: 11, fontWeight: "800" }, search: { marginTop: 16, minHeight: 52, paddingHorizontal: 15, borderWidth: 1, borderRadius: 18, flexDirection: "row-reverse", alignItems: "center", marginBottom: 13 }, input: { flex: 1, marginRight: 9, fontSize: 14, writingDirection: "rtl" }, notice: { textAlign: "right", fontSize: 11, fontWeight: "700", marginBottom: 10 }, surah: { minHeight: 70, borderRadius: 19, borderWidth: 1, padding: 10, flexDirection: "row-reverse", alignItems: "center", marginBottom: 8 }, surahMain: { flex: 1, flexDirection: "row-reverse", alignItems: "center" }, number: { width: 34, height: 34, borderRadius: 12, alignItems: "center", justifyContent: "center" }, numberText: { fontSize: 12, fontWeight: "900" }, surahCopy: { flex: 1, alignItems: "flex-end", marginHorizontal: 10 }, surahTitle: { width: "100%", textAlign: "right", fontSize: 14, fontWeight: "900" }, surahMeta: { width: "100%", textAlign: "right", fontSize: 11, marginTop: 3 }, download: { width: 32, justifyContent: "center", alignItems: "center" }, pressed: { opacity: .72, transform: [{ scale: .98 }] } });
