import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";

import { AudioCard } from "@/components/audio-card";
import { ScreenContainer } from "@/components/screen-container";
import { getRadioAudioItem } from "@/lib/quran-catalog";
import { useQuranContent } from "@/lib/quran-content-context";
import { useQuranTheme } from "@/lib/quran-theme";

export default function ListenScreen() {
  const { colors } = useQuranTheme(); const { catalog, loading, error, refresh } = useQuranContent(); const [query, setQuery] = useState("");
  const programs = useMemo(() => (catalog?.radios ?? []).filter((program) => program.name.includes(query.trim())).map(getRadioAudioItem), [catalog?.radios, query]);
  return <ScreenContainer style={{ backgroundColor: colors.background }}><FlatList data={programs} keyExtractor={(item) => item.id} renderItem={({ item }) => <AudioCard item={item} />} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void refresh()} tintColor={colors.emerald} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<View><Text style={[styles.title, { color: colors.text }]}>المكتبة الإذاعية</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>برامج وتسجيلات مفهرسة في مكتبة Cloudflare بعد التحقق من المصدر والحقوق.</Text><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialCommunityIcons name="magnify" color={colors.textMuted} size={21} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث باسم البرنامج" placeholderTextColor={colors.textMuted} style={[styles.input, { color: colors.text }]} textAlign="right" returnKeyType="done" /></View>{catalog ? <View style={[styles.liveNotice, { backgroundColor: colors.emeraldSoft }]}><MaterialCommunityIcons name="shield-check-outline" size={16} color={colors.emerald} /><Text style={[styles.liveText, { color: colors.emerald }]}>{catalog.radios.length} ملفًا إذاعيًا معتمدًا في الفهرس</Text></View> : null}</View>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surfaceMuted }]}>{loading ? <ActivityIndicator color={colors.emerald} /> : <><MaterialCommunityIcons name="radio-off" size={30} color={colors.gold} /><Text style={[styles.emptyText, { color: colors.textMuted }]}>{error ?? "لا توجد برامج إذاعية معتمدة في المكتبة حتى الآن."}</Text><Pressable onPress={() => void refresh()} style={[styles.retry, { backgroundColor: colors.emerald }]}><Text style={styles.retryText}>تحديث الفهرس</Text></Pressable></>}</View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 176 }, title: { textAlign: "right", fontWeight: "900", fontSize: 28, lineHeight: 36 }, subtitle: { textAlign: "right", marginTop: 4, fontSize: 13, lineHeight: 20 }, search: { marginTop: 18, minHeight: 52, paddingHorizontal: 15, borderWidth: 1, borderRadius: 18, flexDirection: "row-reverse", alignItems: "center" }, input: { flex: 1, marginRight: 9, fontSize: 14, writingDirection: "rtl" }, liveNotice: { marginTop: 13, height: 37, borderRadius: 13, paddingHorizontal: 12, flexDirection: "row-reverse", alignItems: "center", gap: 7 }, liveDot: { width: 7, height: 7, borderRadius: 4 }, liveText: { fontSize: 11, fontWeight: "800" }, empty: { marginTop: 24, padding: 24, borderRadius: 22, alignItems: "center", gap: 10 }, emptyText: { textAlign: "center", fontSize: 12, lineHeight: 19 }, retry: { height: 38, borderRadius: 13, paddingHorizontal: 14, justifyContent: "center" }, retryText: { color: "#FFF", fontWeight: "800", fontSize: 12 } });
