import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { AudioCard } from "@/components/audio-card";
import { ScreenContainer } from "@/components/screen-container";
import { categories, stations } from "@/lib/quran-data";
import { useQuranTheme } from "@/lib/quran-theme";

export default function ListenScreen() { const { colors } = useQuranTheme(); const [query, setQuery] = useState(""); const [category, setCategory] = useState<string>("الكل"); const items = useMemo(() => stations.filter((item) => (category === "الكل" || item.category === category || (category === "قصص" && item.kind === "story")) && `${item.title} ${item.subtitle}`.includes(query.trim())), [category, query]); return <ScreenContainer style={{ backgroundColor: colors.background }}><FlatList data={items} keyExtractor={(item) => item.id} renderItem={({ item }) => <AudioCard item={item} />} contentContainerStyle={styles.content} showsVerticalScrollIndicator={false} ListHeaderComponent={<><Text style={[styles.title, { color: colors.text }]}>استمع الآن</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>محطات مختارة لترافق لحظاتك الهادئة</Text><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialCommunityIcons name="magnify" color={colors.textMuted} size={21} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث عن محطة أو قصة" placeholderTextColor={colors.textMuted} style={[styles.input, { color: colors.text }]} textAlign="right" returnKeyType="done" /></View><View style={styles.chips}>{categories.filter((name) => name !== "تلاوات").map((name) => <Pressable key={name} onPress={() => setCategory(name)} style={({ pressed }) => [styles.chip, { backgroundColor: category === name ? colors.emerald : colors.surface, borderColor: category === name ? colors.emerald : colors.border }, pressed && styles.pressed]}><Text style={[styles.chipText, { color: category === name ? "#FFF" : colors.text }]}>{name}</Text></Pressable>)}</View><Text style={[styles.count, { color: colors.textMuted }]}>{items.length} عناصر متاحة</Text></>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surfaceMuted }]}><Text style={[styles.emptyText, { color: colors.textMuted }]}>لم نجد نتيجة مطابقة. جرّب عبارة أخرى.</Text></View>} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 176 }, title: { textAlign: "right", fontWeight: "900", fontSize: 28, lineHeight: 36 }, subtitle: { textAlign: "right", marginTop: 4, fontSize: 13, lineHeight: 20 }, search: { marginTop: 18, minHeight: 52, paddingHorizontal: 15, borderWidth: 1, borderRadius: 18, flexDirection: "row-reverse", alignItems: "center" }, input: { flex: 1, marginRight: 9, fontSize: 14, writingDirection: "rtl" }, chips: { flexDirection: "row-reverse", gap: 8, marginTop: 14 }, chip: { paddingHorizontal: 15, height: 36, borderRadius: 14, borderWidth: 1, justifyContent: "center" }, chipText: { fontSize: 12, fontWeight: "800" }, count: { textAlign: "right", fontSize: 11, fontWeight: "700", marginVertical: 14 }, empty: { padding: 22, borderRadius: 20 }, emptyText: { textAlign: "center", fontSize: 13 }, pressed: { opacity: .75, transform: [{ scale: .98 }] } });
