import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, RefreshControl, StyleSheet, Text, TextInput, View } from "react-native";

import { ArtworkOrb } from "@/components/artwork-orb";
import { ScreenContainer } from "@/components/screen-container";
import { useQuranContent } from "@/lib/quran-content-context";
import { useQuranTheme } from "@/lib/quran-theme";

export default function RecitersScreen() {
  const router = useRouter(); const { colors } = useQuranTheme(); const { catalog, loading, error, refresh } = useQuranContent(); const [query, setQuery] = useState("");
  const items = useMemo(() => (catalog?.reciters ?? []).filter((item) => item.name.includes(query.trim())), [catalog?.reciters, query]);
  return <ScreenContainer style={{ backgroundColor: colors.background }}><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => void refresh()} tintColor={colors.emerald} />} renderItem={({ item, index }) => <Pressable onPress={() => router.push(`/reciter/${item.id}` as never)} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><ArtworkOrb color={["#0D7869", "#B8842D", "#3C6E8F", "#637E51"][index % 4]} kind="reciter" size={54} /><View style={styles.copy}><Text style={[styles.name, { color: colors.text }]}>{item.name}</Text><Text style={[styles.meta, { color: colors.textMuted }]}>{item.availableSurahIds.length} سورة كاملة · مصدر موثق</Text></View><MaterialCommunityIcons name="chevron-left" size={23} color={colors.textMuted} /></Pressable>} ListHeaderComponent={<View><Text style={[styles.title, { color: colors.text }]}>القراء</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>اختر قارئًا لتظهر لك جميع السور المتاحة لديه</Text><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialCommunityIcons name="magnify" color={colors.textMuted} size={21} /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث باسم القارئ" placeholderTextColor={colors.textMuted} style={[styles.input, { color: colors.text }]} textAlign="right" returnKeyType="done" /></View>{catalog ? <Text style={[styles.source, { color: colors.gold }]}>فهرس حي: {catalog.surahs.length} سورة · {catalog.reciters.length} قارئًا</Text> : null}</View>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surfaceMuted }]}>{loading ? <ActivityIndicator color={colors.emerald} /> : <><MaterialCommunityIcons name="cloud-off-outline" size={28} color={colors.gold} /><Text style={[styles.emptyText, { color: colors.textMuted }]}>{error ?? "لا توجد بيانات محفوظة بعد. اسحب للتحديث."}</Text><Pressable onPress={() => void refresh()} style={[styles.retry, { backgroundColor: colors.emerald }]}><Text style={styles.retryText}>إعادة المحاولة</Text></Pressable></>}</View>} showsVerticalScrollIndicator={false} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 176 }, title: { textAlign: "right", fontWeight: "900", fontSize: 28, lineHeight: 36 }, subtitle: { textAlign: "right", marginTop: 4, fontSize: 13, lineHeight: 20 }, search: { marginTop: 18, minHeight: 52, paddingHorizontal: 15, borderWidth: 1, borderRadius: 18, flexDirection: "row-reverse", alignItems: "center" }, input: { flex: 1, marginRight: 9, fontSize: 14, writingDirection: "rtl" }, source: { textAlign: "right", fontSize: 11, fontWeight: "800", marginVertical: 14 }, card: { minHeight: 76, borderWidth: 1, borderRadius: 22, padding: 11, flexDirection: "row-reverse", alignItems: "center", marginBottom: 10 }, copy: { flex: 1, alignItems: "flex-end", marginHorizontal: 11 }, name: { width: "100%", textAlign: "right", fontWeight: "900", fontSize: 15 }, meta: { width: "100%", textAlign: "right", fontSize: 11, marginTop: 4 }, empty: { marginTop: 24, padding: 24, borderRadius: 22, alignItems: "center", gap: 10 }, emptyText: { textAlign: "center", fontSize: 12, lineHeight: 19 }, retry: { height: 38, borderRadius: 13, paddingHorizontal: 14, justifyContent: "center" }, retryText: { color: "#FFF", fontWeight: "800", fontSize: 12 }, pressed: { opacity: .72, transform: [{ scale: .98 }] } });
