import MaterialCommunityIcons from "@expo/vector-icons/MaterialCommunityIcons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useMemo } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { ArtworkOrb } from "@/components/artwork-orb";
import { ScreenContainer } from "@/components/screen-container";
import { usePlayer } from "@/lib/player-context";
import { findApprovedAudioItem } from "@/lib/quran-catalog";
import { useQuranContent } from "@/lib/quran-content-context";
import { useQuranTheme } from "@/lib/quran-theme";

export default function ItemDetailsScreen() {
  const router = useRouter();
  const { id } = useLocalSearchParams<{ id: string }>();
  const { catalog } = useQuranContent();
  const item = useMemo(() => findApprovedAudioItem(catalog, id ?? ""), [catalog, id]);
  const { colors } = useQuranTheme();
  const { current, isPlaying, favorites, playlists, playItem, togglePlayback, toggleFavorite, addToPlaylist } = usePlayer();
  if (!item) return <ScreenContainer style={{ backgroundColor: colors.background }}><View style={styles.empty}><Text style={[styles.emptyText, { color: colors.textMuted }]}>هذا المحتوى غير متاح.</Text><Pressable onPress={() => router.back()} style={[styles.return, { backgroundColor: colors.emerald }]}><Text style={styles.returnText}>عودة</Text></Pressable></View></ScreenContainer>;
  const isCurrent = current?.id === item.id; const favorite = favorites.includes(item.id);
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} style={{ backgroundColor: colors.background }}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.top}><Pressable onPress={() => router.back()} style={({ pressed }) => [styles.icon, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><MaterialCommunityIcons name="chevron-right" size={25} color={colors.text} /></Pressable><Text style={[styles.topLabel, { color: colors.textMuted }]}>تفاصيل المحتوى</Text><Pressable onPress={() => toggleFavorite(item.id)} style={({ pressed }) => [styles.icon, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><MaterialCommunityIcons name={favorite ? "heart" : "heart-outline"} size={21} color={favorite ? colors.gold : colors.text} /></Pressable></View>
    <View style={[styles.hero, { backgroundColor: item.color }]}><Text style={styles.glyph}>۞</Text><ArtworkOrb color="rgba(255,255,255,.14)" kind={item.kind} size={116} /></View>
    <Text style={[styles.title, { color: colors.text }]}>{item.title}</Text><Text style={[styles.subtitle, { color: colors.textMuted }]}>{item.subtitle}</Text>
    <Pressable onPress={() => void (isCurrent ? togglePlayback() : playItem(item))} style={({ pressed }) => [styles.primary, { backgroundColor: colors.emerald }, pressed && styles.pressed]}><MaterialCommunityIcons name={isCurrent && isPlaying ? "pause" : "play"} size={22} color="#FFF" /><Text style={styles.primaryText}>{isCurrent && isPlaying ? "إيقاف مؤقت" : "تشغيل الآن"}</Text></Pressable>
    <View style={[styles.info, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.infoRow}><Text style={[styles.infoValue, { color: colors.textMuted }]}>{item.kind === "station" ? "بث مباشر" : item.durationLabel ?? "تلاوة"}</Text><Text style={[styles.infoLabel, { color: colors.text }]}>النوع</Text></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><View style={styles.infoRow}><Text style={[styles.infoValue, { color: colors.textMuted }]}>{item.category}</Text><Text style={[styles.infoLabel, { color: colors.text }]}>التصنيف</Text></View></View>
    <Text style={[styles.section, { color: colors.text }]}>أضف إلى قائمة تشغيل</Text>{playlists.length ? playlists.map((playlist) => <Pressable key={playlist.id} onPress={() => addToPlaylist(playlist.id, item.id)} style={({ pressed }) => [styles.playlist, { backgroundColor: colors.surfaceMuted }, pressed && styles.pressed]}><MaterialCommunityIcons name="playlist-plus" size={22} color={colors.gold} /><Text style={[styles.playlistText, { color: colors.text }]}>{playlist.title}</Text></Pressable>) : <View style={[styles.emptyList, { backgroundColor: colors.goldSoft }]}><Text style={[styles.emptyListText, { color: colors.textMuted }]}>أنشئ قائمة من «مكتبتي» ثم عد لإضافة هذا المحتوى.</Text></View>}
  </ScrollView></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 36 }, top: { flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, topLabel: { fontSize: 11, fontWeight: "800" }, icon: { width: 42, height: 42, borderRadius: 15, borderWidth: 1, alignItems: "center", justifyContent: "center" }, hero: { height: 246, borderRadius: 34, marginTop: 28, overflow: "hidden", alignItems: "center", justifyContent: "center" }, glyph: { position: "absolute", color: "rgba(255,255,255,.15)", fontSize: 230, lineHeight: 240 }, title: { textAlign: "center", fontSize: 25, lineHeight: 34, fontWeight: "900", marginTop: 24 }, subtitle: { textAlign: "center", fontSize: 13, lineHeight: 21, marginTop: 7 }, primary: { height: 52, borderRadius: 18, marginTop: 24, flexDirection: "row-reverse", alignItems: "center", justifyContent: "center", gap: 7 }, primaryText: { color: "#FFF", fontSize: 14, fontWeight: "900" }, info: { marginTop: 18, borderRadius: 20, borderWidth: 1, paddingHorizontal: 15 }, infoRow: { minHeight: 52, flexDirection: "row-reverse", alignItems: "center", justifyContent: "space-between" }, infoLabel: { fontSize: 13, fontWeight: "800" }, infoValue: { fontSize: 12 }, divider: { height: 1 }, section: { textAlign: "right", fontSize: 17, fontWeight: "900", marginTop: 24, marginBottom: 10 }, playlist: { minHeight: 52, borderRadius: 16, paddingHorizontal: 14, flexDirection: "row-reverse", alignItems: "center", gap: 9, marginBottom: 8 }, playlistText: { fontSize: 13, fontWeight: "800" }, emptyList: { borderRadius: 16, padding: 14 }, emptyListText: { textAlign: "right", fontSize: 12, lineHeight: 19 }, pressed: { opacity: .75, transform: [{ scale: .98 }] }, empty: { flex: 1, alignItems: "center", justifyContent: "center", gap: 14 }, emptyText: { fontSize: 15 }, return: { height: 44, borderRadius: 15, paddingHorizontal: 18, justifyContent: "center" }, returnText: { color: "#FFF", fontWeight: "800" } });
